project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: setup.qmd
        text: Set up your framework
      - href: git1.qmd
        text: Basics in git, working alone
      - href: git2.qmd
        text: Working collaboratively
    right:
      - href: https://github.com/MarieEtienne/stats-reminders
        text: Stats Reminders
       
format:
  html:
    theme: flatly
    linkcolor: "#c0392b"
    fontcolor: "#057174"
    css: theme.css
    toc: true