project:
  type: website

website:
  navbar:
    left:        
    - href: index.qmd
      text: Home
    - text: Courses
      menu:
        - href: introduction.qmd
          text: Introduction
        - href: quarto.qmd
          text: Quarto
        - href: setup.qmd
          text: Set up your framework
        - href: linux_survival_kit.qmd
          text: CLI survival kit      
        - href: git1.qmd
          text: Basics in git, working alone
        - href: git2.qmd
          text: Working collaboratively
    right:
      - href: https://github.com/MarieEtienne/OCR_TP
        text: OCR Assignment
       
format:
  html:
    theme: flatly
    linkcolor: "#c0392b"
    fontcolor: "#057174"
    css: theme.css
    toc: true