---
title: "R : premier pas"
description: |
  Ce site contient les liens vers les données et les supports de cours pour la formation. 
output: 
  html_document:
   toc: false
   logo: ../courses_tools/resources/common_figs/LogoAgrocampusOuest.jpg
   number_sections: false
   highlight: tango
   css: style.css
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```


# Installation logiciels pour la formation


Il est préférable de commencer par installer R avant d’installer RStudio.
Installation de R
Windows : le premier lien sur la page  http://cran.r-project.org/bin/windows/base/  permet de télécharger programme d’installation. Une fois le programme d’installation lancé, il suffira d’installer R avec les options par défaut. 
Mac OS X :les fichiers d’installation sont disponibles à http://cran.r-project.org/bin/macosx/.
Linux :  R est disponible dans le  gestionnaire de paquets, cela pouvant dépendre d’une distribution de Linux à une autre.
Installation de RStudio

La page  http://www.rstudio.com/products/rstudio/download/ permet de télécharger  la dernière version stable de Rstudio. Il faut choisir l’installateur correspondant à votre système d’exploitation et suivre la procédure.


# Les données 

Toutes les données qui seront utilisées dans le cours sont diponibles sur [cette page](https://marieetienne.github.io/data.html)


# Les supports de cours 

Le cours aborde

- [Une introduction](_presentation/introduction.html)
- [La manipulation de données](_presentation/manip.html)
- [la visualisation de données](_presentation/visu.html)
- [Une introduction au modèle linéaire](_presentation/modelelineaire.html)



# Fiches protocole

- [Importation des données](http://marieetienne.github.io/h_import_data.html)
