on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build website with quarto
    runs-on: ubuntu-latest
    container: mpetienne/topics:latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    # A essayer pour le cache    
    # - name: Cache R packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.R/library
    #     key: ${{ runner.os }}-r-packages-${{ hashFiles('r-packages.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-r-packages-
    # 
    # - name: Install R packages
    #   run: |
    #     Rscript -e 'packages <- scan("r-packages.txt", what = character()); install.packages(packages, repos = "https://cran.rstudio.com")'

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('Factoshiny', 'RefManageR', 'wesanderson', 'palmerpenguins', 'plotly'))"
          Rscript -e "install.packages(c('reticulate', 'ggpubr', 'GGally', 'xaringanExtra', 'flipbookr', 'ggrepel'))"
      - name: Additional Python packages
        run: |
          pip install numpy scipy pandas seaborn scikit-learn statsmodels palmerpenguins 
      - name: Generate slides
        run: "quarto render"
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
